server.port: 9088
file:
  uploadPath: /mydata/upload/
  uploadPrefix : 'd:'
  urlPath: http://192.168.0.49:9088

spring:
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
robot.innerpath: /home/uucall/callcenter/
